### ISSUE TITLE
Add the possibility to disable logs

### ISSUE THREAD

**Issue by nbossard** [Orange-OpenSource/orange-trust-badge-android#10]
Hello, 
I would like to add the possibility to disable logs in production as we can see in app logcat lot of info : 

 11-22 14:31:26.020 9582-9582/com.orange.mojfunbox.pl D/TrustBadgeManager: getSpecificPermission
 11-22 14:31:26.020 9582-9582/com.orange.mojfunbox.pl D/TrustBadgeManager: trustBadgeElement.getElementType() equals USAGE
 11-22 14:31:26.120 9611-9611/com.orange.mojfunbox.pl:Engagement I/CrashlyticsCore: Initializing Crashlytics 2.3.13.145
 11-22 14:31:26.356 9611-9611/com.orange.mojfunbox.pl:Engagement D/PermissionManager: initPermissionList for context com.orange.mylivebox.fr.app.GrdApplication@e8423c
 11-22 14:31:26.358 9611-9611/com.orange.mojfunbox.pl:Engagement D/PermissionManager: requestedPermissions is not null
 11-22 14:31:26.358 9611-9611/com.orange.mojfunbox.pl:Engagement D/PermissionManager: Adding permission : android.permission.READ_PHONE_STATE
 11-22 14:31:26.358 9611-9611/com.orange.mojfunbox.pl:Engagement D/PermissionManager: Looking group for permission android.permission.READ_PHONE_STATE

**Comment by nbossard** [comment]
I added a Logger class and replaced all calls to Android.util.log by this class, but I don't know where to put the switch, I originally thought i would use the 
debug ==> log / release ==> not log 
but as this is a library it is always built in release mode...
Where do you think it would be better to place the switch ? in the TrustBadgeManager intialisation?

**Comment by nbossard** [comment]
Made a pull request for it, see #11

**Comment by vboesch** [comment]
Done, but written in kotlin
