### ISSUE TITLE
Orange Nura device under Android 4.4.2 crash

### ISSUE THREAD

**Issue by kun-qian** [Orange-OpenSource/orange-trust-badge-android#6]
Hello,

I find that OtbTermsFragment crashed on Orange Nura device under Android 4.4.2.
Would you please have a look?

Best,

**Comment by kun-qian** [comment]
No one maintains this repo. OMG Orange Opensource

**Comment by vboesch** [comment]
Sorry, We had no time to answer, but this repo is kept up to date with new releases
