### ISSUE TITLE
OtbActivity leaks via its BadgeListener entry

### ISSUE THREAD

**Issue by jilles-sg** [Orange-OpenSource/orange-trust-badge-android#7]
OtbActivity has `TrustBadgeManager.INSTANCE.addBadgeListener(this);` in its `onCreate()`, but I do not see where this is removed. I suggest removing it in `onDestroy()`.

A workaround in apps is possible by calling `clearBadgeListener` in an OtbActivity subclass's `onDestroy()`.

**Comment by ssandon** [comment]
Problem is still in v1.2.0.

If activity is started via intent the problem occurred.
