### ISSUE TITLE
accessibility - recommended age is not vocalised by talkback

### ISSUE THREAD

**Issue by Pascale22** [Orange-OpenSource/orange-trust-badge-android#9]
![otb_accessibility|120px](https://user-images.githubusercontent.com/12068186/32483909-34304e7a-c39e-11e7-90ad-edfe451c1651.png)

**Comment by Pascale22** [comment]
The component is readable by talkback... except this information.

**Comment by vboesch** [comment]
This information is no longer displayed in the v2 version so bug should be closed
